language: node_js
node_js:
  - "0.10"
sudo: false
env:
  global:
  - secure: IU/QvZF23o09OLh8LJ9lu+2oZq7P81n7TcWWQ49VOWs7SkWAlVyhGcMeZ9z3Zl4bBaQW7jmjqWmbghFJN+q0XNn5PG/nw0SDGxlz+1pGaGmcc/rUGmOwywBNoqX2ag93/oBz0IHgaWCcn4Pj/pax91NlUjsuTUCMlpS0zravqMU=
  - secure: OrHIql9/GHFdcBcBYLheJU87QzloC2El7CG5xlL0zGkcmUiZvPA8pOFGVVnrTnuGU5Zu2BzC7qDKYMsJXM8aMiGSvfK6Afq5O1LnwJOD0Qcbf9S98iytQDxXuO05lFnLHZwJUS3C6naFN+8ZwEu4o7t8fK6ULQeANY3CragONQI=
  - secure: RABlSo6VtHKTwfazNOfzljidZDkYXLxMNYpSdipsEoqbKgb3Gz+GpzcYt/jE0D6IMPpnm2mw9iBHvVdZ5f2CrUkLFZTvYCmBPlpF4oY0fugLcGYosfas2GK9qqc6czaTNWUz69KP/Txg78PdfJ79eTKYRtkQFCvYfZhiaJlqN14=
before_install: npm install -g grunt-cli
install: npm install
after_success: grunt saucelabs
